[conf]
# Determines whether the bot is in sandbox or live mode
is_sandbox = true

# Coinbase specification for the bot
[conf.production.coinbase]
url = "https://api.pro.coinbase.com"
websocket_url = "wss://ws-feed.pro.coinbase.com"
api_key = "key"
api_secret = "secret"
api_passphrase = "passphrase"

# Coinbase Sandbox specification
[conf.sandbox.coinbase]
url = "https://api-public.sandbox.pro.coinbase.com"
websocket_url = "wss://ws-feed-public.sandbox.pro.coinbase.com"
api_key = "key"
api_secret = "secret"
api_passphrase = "passphrase"

# Which channels to listen to
[conf.websocket]
channels = [
        { name = "heartbeat", product_ids = ["BTC-USD"] },
        #    { name = "status", product_ids = ["BTC-USD"] },
        #    { name = "ticker", product_ids = ["BTC-USD"] },
        #    { name = "level2", product_ids = ["BTC-USD"] },
        #    { name = "user", product_ids = ["BTC-USD"] },
        #    { name = "full", product_ids = ["BTC-USD"] }
]

# Database information
[conf.production.database]
type = "postgres"
name = "lucrum"
host = "host"
port = 5432
user = "lucrum"
passphrase = "passphrase"
# How many attempts to make before giving up
attempts = 5
# How long to wait between requests in seconds
connection_wait = 5

# Database information
[conf.sandbox.database]
type = "postgres"
name = "sandbox_lucrum"
host = "localhost"
port = 5432
user = "lucrum"
passphrase = "passphrase"
# How many attempts to make before giving up
attempts = 5
# How long to wait between requests in seconds
connection_wait = 5

# Determines if the bot should be daemonized
[daemon]
daemonize = false
pid_file = "pid/lucrum.pid"
pid_file_perms = "0644"
log_file = "logs/lucrum.log"
log_file_perms = "0644"

# Determines if the websocket portion should be daemonized
[websocket_daemon]
daemonize = false
pid_file = "pid/websocket.pid"
pid_file_perms = "0644"
log_file = "logs/websocket.log"
log_file_perms = "0644"